[package]
name = "chess_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
chess_core = { path = "../chess_core" }
bevy = {version = "0.13.2", features = ["dynamic_linking"]}
bevy_mod_picking = "0.18.2"
thiserror = "2.0.12"
crossbeam-channel = "0.5.15"
